In [3]:
import pandas as pd

In [4]:
import numpy as np

In [1]:
df_base = {'Nome': ['Joao', 'Pedro', 'Alicia'], 'Idade':[23,44,32]}

In [5]:
df = pd.DataFrame(df_base)
df

Nome  Idade
0    Joao     23
1   Pedro     44
2  Alicia     32

1. Crie um array NumPy com 10 elementos inteiros aleatórios no intervalo [0, 100] e exiba os valores e o tipo de dado do array.

In [35]:
arr = np.random.randint(0,100, size = 10)
arr

array([58, 52, 31,  7, 34, 92, 20, 88, 90, 13])

In [11]:
print(arr.dtype)

int32


2. Crie uma matriz de 5x5 com valores aleatórios de [0,1) e encontre o valor mínimo, máximo e a média da matriz.

In [17]:
arr_2 = np.random.rand(5,5)
arr_2

array([[0.61506986, 0.67733875, 0.88153117, 0.86676234, 0.77304107],
       [0.24326205, 0.29277422, 0.53505209, 0.48144688, 0.68660127],
       [0.35418123, 0.96850106, 0.42689255, 0.12998519, 0.00654932],
       [0.6384677 , 0.63404414, 0.03608876, 0.31585152, 0.90496853],
       [0.29600185, 0.68896057, 0.9839829 , 0.39916488, 0.9680201 ]])

In [28]:
arr_max = arr_2.max()
print(arr_max)

#   OU 

np.max(arr_2)

0.9839828956549618


0.9839828956549618

In [30]:
arr_min = arr_2.min()
print(arr_min)

#OU

np.min(arr_2)

0.006549321756018633


0.006549321756018633

In [31]:
arr_med = arr_2.mean()
print(arr_med)

#OU

np.mean(arr_2)

0.5521815994967648


0.5521815994967648

In [32]:
arr_2.ndim #DIMENSAO DA MATRIZ

2

In [33]:
arr_2.shape

(5, 5)

3. Crie um array com 10 elementos aleatórios no intervalo [0, 1]. Em seguida, crie um novo array com os elementos do primeiro array multiplicados por 10 e convertidos para inteiro.

In [5]:
arr_3 = np.random.rand (10)
arr_3

array([0.2476228 , 0.02224184, 0.3514022 , 0.2701577 , 0.27629563,
       0.76240538, 0.2080644 , 0.95898211, 0.88377588, 0.43894148])

In [6]:
arr_4 = (arr_3 * 10)
arr_4

array([2.47622805, 0.22241836, 3.514022  , 2.70157704, 2.76295633,
       7.62405378, 2.08064395, 9.58982111, 8.83775876, 4.3894148 ])

In [10]:
arr_final = np.array(arr_4, dtype='int') #TORNAR A MATRIZ FLOAT PARA INT
print(arr_final)
print(arr_final.dtype)

[2 0 3 2 2 7 2 9 8 4]
int32


In [11]:
arr_final.astype(int) #TORNAR A MATRIZ FLOAT PARA INT

array([2, 0, 3, 2, 2, 7, 2, 9, 8, 4])

4. Crie um array de duas dimensões com shape (3, 3) e valores aleatórios inteiros no intervalo [0, 9]. Substitua todos os elementos da segunda linha por -1.

In [14]:
arr_5 = np.random.randint(0,10, (3,3))
arr_5

array([[9, 0, 4],
       [2, 9, 3],
       [7, 4, 5]])

In [18]:
arr_5 [1,:] = -1 #SUBSTITUIR O VALOR DE UMA LINHA POR -1
arr_5

array([[ 9,  0,  4],
       [-1, -1, -1],
       [ 7,  4,  5]])

5. Crie um DataFrame com as seguintes informações:
 - Coluna "fruta": "Banana", "Maça", "Pera"
 - Coluna "preco": 7.90, 10.20, 11.80
 - Coluna "quantidade": 12, 3, 4

In [19]:
lista = {'Frutas': ['Banana', 'Maça', 'Pera'], 'Preco':[7.90,10.20,11.80],'Qnt':[12,3,4]}

In [20]:
df = pd.DataFrame(lista)
df

Frutas  Preco  Qnt
0  Banana    7.9   12
1    Maça   10.2    3
2    Pera   11.8    4