                                           INTRODUÇÃO A NUMPY E PANDAS 

ARRAY NATIVO DO PYTHON

In [10]:
from array import array

In [4]:
a = array('i', [1,2,3,4])

In [5]:
a * 2 #NÃO DOBRA A IDADE, APENAS CONCATENA

array('i', [1, 2, 3, 4, 1, 2, 3, 4])

ARRAY DO NUMPY

In [11]:
import numpy as np

In [7]:
arr = np.array([18,22,33,44]) #COM LISTA, pode ser tupla

In [9]:
arr * 2 #AQUI ELE DOBRA VETORIALMENTE

array([36, 44, 66, 88])

NDARRAY

In [24]:
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matriz)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(tensor)



[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [25]:
print(matriz.shape) #TAMANHO DO ARRAY
print(tensor.shape)

(3, 3)
(2, 2, 2)


In [27]:
print(matriz.dtype)
print(tensor.dtype)

int32
int32


In [29]:
print(matriz.ndim) #QUANTAS DIMENSOES

2


TIPOS DE CRIACAO DE Ndarrays

In [32]:
ones = np.ones((3,3)) #CRIA 2 DIMENSOES COM O NUM 1 DE X,X
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [34]:
full = np.full((3,2),42) #CRIA 3X2 COM O NUMERO 42
print(full)

[[42 42]
 [42 42]
 [42 42]]


In [35]:
zeros = np.zeros((2,3)) #IGUAL AO ONES
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [36]:
np.diag(matriz) #DIAGONAL DA MATRIZ

array([1, 5, 9])

GERAÇÃO DE VALORES ALEATORIOS

numpy.randon.rand : gera valores aleatorios no intervalo [0,1]

In [35]:
np.random.rand(2,2)

array([[0.46197933, 0.7878516 ],
       [0.41877433, 0.98488827]])

numpy.random.randint: gera valores inteiros aleatorios em um intervalo especificado em uma forma especificada.

In [36]:
np.random.randint(0,10, size=(10))

array([7, 2, 5, 6, 2, 1, 0, 0, 5, 4])

INDEXAÇÃO DE ARRAYS

In [39]:
matriz_ex = np.array([[1,2,3],[4,5,6]])

In [41]:
matriz_ex

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
matriz_ex[0,0]

1

FATIAMENTO

In [43]:
print('Indexação 1:')
print(matriz_ex[0:2, 1:3])
print('Indexação 2:')
print(matriz_ex[:, 0:2])
print('Indexação 3:')
print(matriz_ex[1, :])


Indexação 1:
[[2 3]
 [5 6]]
Indexação 2:
[[1 2]
 [4 5]]
Indexação 3:
[4 5 6]


OPERAÇÕES COM MATRIZES DE ARRAYS

In [44]:
matriz_ex.sum() #SOMA

21

In [45]:
matriz_ex.max() #ELEMENTOS MAXIMOS

6

In [46]:
matriz_ex.mean() #MEDIA DE TODOS OS ELEMENTOS DA MATRIZ

3.5

In [47]:
matriz_ex.std() #DESVIO PADRAO

1.707825127659933

In [48]:
matriz_ex.var() #VARIANCIA

2.9166666666666665

                                                                PANDAS

SERIES 

In [12]:
arr = np.array(range(10,15))
arr

array([10, 11, 12, 13, 14])

In [13]:
import pandas as pd

In [14]:
pd.Series(arr)

0    10
1    11
2    12
3    13
4    14
dtype: int32

In [15]:
serie_a = pd.Series(np.array(range(10,15))) #OUTRO JEITO DE REALIZAR A CRIAÇAO
serie_a

0    10
1    11
2    12
3    13
4    14
dtype: int32

In [16]:
type(serie_a)

pandas.core.series.Series

In [17]:
serie_a.index

RangeIndex(start=0, stop=5, step=1)

In [18]:
serie_a

0    10
1    11
2    12
3    13
4    14
dtype: int32

In [22]:
serie_b = pd.Series(np.array([5,6,7,8]), index=['a','b','c','d']) #MUDANDO OS INDICES DA SERIE

In [21]:
serie_b

a    5
b    6
c    7
d    8
dtype: int32

                                                       DATAFRAME - PANDAS

E uma estrutura de dados bidimensional que pode armazenar dados de diferentes tipos em diferentes colunas. Cada coluna ou linha pode ser relacionada a uma Serie, portanto DataFrame e a juncao de varias series.                                 

In [24]:
mat = np.array([[1,2,3],[4,5,6]])

In [26]:
df = pd.DataFrame(mat)
df

0  1  2
0  1  2  3
1  4  5  6

In [29]:
df = pd.DataFrame(mat, columns=['col1','col2','col3']) #NOMEANDO AS COLUNAS
df

col1  col2  col3
0     1     2     3
1     4     5     6

In [32]:
df = pd.DataFrame(mat,index=['a','b']) #INDEXANDO OS INDICES
df

0  1  2
a  1  2  3
b  4  5  6